administrator/controllers/DeclarationsController.php
<?php

namespace administrator\controllers;

use common\models\Service;
use common\models\AdminDeclarations;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\helpers\Url;
use Yii;

/**
 * Site controller
 */
class DeclarationsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        $service = new Service();
        $model = new AdminDeclarations();
        $declarations = $service->getDeclarations();
        $items = [];
        foreach ($declarations as $data) {
            $modelData = new AdminDeclarations();
            $modelData->setAttributes($data);
            $items[] = $modelData;
        }
        return $this->render('index', [ 'model' => $model, 'datas' => $items]);
    }

    public function actionCreate() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new AdminDeclarations();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $service = new Service();
            $response = (object) $service->createAdminDeclaration($model);
            if ($response->status['code'] == 1) {
                Yii::$app->session->setFlash('success-message', 'Declaration record successfully created...');
                $url = Url::toRoute(['index']);
                return ['success' => $url];
            } else {
                $model->addError("", "ERROR CODE " . $response->status['code'] . " :: " . $response->status['message']);
            }
        }
        $errorsArry = '';
        foreach ($model->getErrors() as $error) {
            $errorsArry.=$error[0] . "<br/>";
        }
        return ['error' => $errorsArry];
    }

    public function actionDelete($id) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new AdminDeclarations();
        $service = new Service();
        $password = $_POST['password'];
        if (!empty($password)) {
            $response = (Object) $service->deleteDeclaration($id, $password);
            if ($response->status['code'] == 200) {
                $url = Url::toRoute(['index']);
                \Yii::$app->getSession()->setFlash('success-message', "Record #" . $id . " successfully deleted.");
                return ['success' => $url];
            } else {
                $model->addError("", "Error Code " . $response->status['code'] . " :: " . $response->status['message']);
            }
        } else {
            $model->addError("", "Password cannot be blank");
        }
        $errorsArry = '';
        foreach ($model->getErrors() as $error) {
            $errorsArry.= $error[0] . "<br/>";
        }
        return ['error' => $errorsArry];
    }

}

administrator/views/declarations/_declarations.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\helpers\Json;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([
        'allModels' => $datas,
            ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'description',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update}&nbsp;&nbsp;{delete}&nbsp;&nbsp;',
            'buttons' => [
                'update' => function($url, $model) {
                    $data = Json::encode($model->getAttributes());
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['data-whatever' => $data, 'data-toggle' => "modal", 'data-target' => "#DeclarationModal", 'title' => Yii::t('yii', 'Update'),]);
                },
                'delete' => function($url, $model) {
                    $url = Url::toRoute(['declarations/delete', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['data-whatever' => $url, 'data-toggle' => "modal", 'data-target' => "#DeleteRedirectModal", 'title' => Yii::t('yii', 'Delete'),]);
                },
                ],
            ],
        ],
    ]);
?>
        <!-- Creation Model -->
        <?php
        Modal::begin([
            'id' => 'DeclarationModal',
            'header' => '<h4 class="modal-title" id="create-declaration-modal-header" >Create Declaration</h4>',
            'footer' =>
            Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
            . PHP_EOL .
            Html::button('Create', ['id' => 'register-declaration-btn', 'class' => 'btn btn-primary btn-modal-save']),
        ]);
        ?>
        <?= $this->render('_form', ['model' => $model]) ?>
        <?php Modal::end() ?>


        <!-- Delete Redirect Modal -->
        <?php
        Modal::begin([
            'id' => 'DeleteRedirectModal',
            'header' => '<h4 class="modal-title" >Delete Record</h4>',
            'footer' =>
            Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
            . PHP_EOL .
            Html::button('Delete', ['id' => 'delete-redirect-btn', 'class' => 'btn btn-primary btn-modal-save']),
        ]);
        ?>
        <?= $this->render('@common/views/_delete') ?>
        <?php Modal::end() ?>

administrator/views/declarations/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin([
        'action'=>Yii::$app->urlManager->createUrl(['declarations/create']),
        'id' => 'declaration-model-form',
        'enableClientValidation' => true,
    ]); ?>
<?= Html::activeHiddenInput($model,'id') ?>
<?= $form->field($model, 'description')->textarea() ?>

<?php ActiveForm::end(); ?>
<h2></h2>
<div class="alert alert-danger"  id="error-summary" style="display: none;"></div>
<h2></h2>
<div id="progress-spinner" class="text-center" style="display: none;">
    <?= Html::img('@web/images/ajax-loader.gif', ['alt' => 'progress spinner']) ?>
</div>
<h2></h2>

administrator/views/declarations/index.php
<?php
use yii\helpers\Html;
$this->title = Yii::t('app', 'Declarations');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <div class="row">
                    <div class="col-md-12">
                        <p><?=Html::a('<span class="fa fa-plus"></span> New Declaration', "", ['style'=>'margin-right:10px;','class'=>'btn btn-primary', 'data-toggle'=>"modal",'data-whatever'=>"", 'data-target'=>"#DeclarationModal", 'title' => Yii::t('yii', 'New Declaration'),]);?></p>
                    </div>
                </div>
                <?= $this->render('_declarations', ['datas'=>$datas,'model'=>$model]) ?>
            </div>
        </div>
    </div>
</div>