administrator/controllers/ReportsController.php
<?php

namespace administrator\controllers;

use common\models\Service;
use common\models\Student;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\Filter;
use common\models\Payments;
use common\models\CourseDisplay;
use common\models\ExemptionVerification;
use common\models\ExaminationBooking;
use common\models\DeclarationReport;
use yii\web\Response;
use Yii;

/**
 * Site controller
 */
class ReportsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionExaminationBooking($k = "", $k1 = "", $k2 = "", $k3 = "", $k4 = "", $k5 = "", $k6 = "") {
        $filterModel = new Filter();
        $filterModel->month = empty($k) ? "" : $k;
        $filterModel->year = empty($k1) ? "" : $k1;
        $filterModel->courseType = empty($k2) ? "" : $k2;
        $filterModel->course = empty($k3) ? "" : $k3;
        $filterModel->zone = empty($k4) ? "" : $k4;
        $filterModel->center = empty($k5) ? "" : $k5;
        $filterModel->status = empty($k6) ? "" : $k6;

        $service = new Service();
        $courseTypes = $service->courseTypes();
        $status = $service->getStatus();
        $sittingYears = $service->sittingYears();
        $sittingMonths = $service->sittingMonths();
        $coursesData = $service->getCourseType();
        $courses[0] = "All";
        foreach ($coursesData as $requirement) {
            foreach ($requirement['courseCollection'] as $course) {
                $courses[$course['id']] = $course['name'];
            }
        }
        $exams = $service->getExamBookings($filterModel->courseType, $filterModel->course, $filterModel->year, $filterModel->month, $filterModel->center, $filterModel->status);
        $datas = [];
        foreach ($exams as $data) {
            $model = new ExaminationBooking();
            $model->setAttributes($data);
            $datas[] = $model;
        }

        $zoneData = $service->getZones();
        $zones = $centersArray = [];
        $i = $j = 0;
        foreach ($zoneData as $dt) {
            if ($i == 0 && empty($k4)) {
                $k4 = $dt['id'];
                $zones[''] = "All";
            }
            $i++;
            $zones[$dt['id']] = $dt['name'];
        }
        $sittingCenters = $service->getCenters($k4);

        foreach ($sittingCenters as $center) {
            if ($j == 0 && empty($k5)) {
                $centersArray[''] = "All";
            }
            $j++;
            $centersArray[$center['code']] = $center['name'];
        }

        return $this->render('examination-booking', ['status' => $status, 'zones' => $zones, 'centers' => $centersArray, 'datas' => $datas, 'filterModel' => $filterModel, 'courseTypes' => $courseTypes, 'sittingYears' => $sittingYears, 'sittingMonths' => $sittingMonths, 'courses' => $courses]);
    }

    public function actionExaminationBookingFilter($zone) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $service = new Service();
        $centersArray[] = "All";

        $sittingCenters = $service->getCenters($zone, "");
        foreach ($sittingCenters as $center) {
            $centersArray[$center['code']] = $center['name'];
        }
        return ['success' => $centersArray];
    }

    public function actionStudentRegistration($k = "", $k1 = "") {
        $currentMonth = date("m");
        $currentYear = date("Y");
        $startDate = empty($k) ? ($currentYear . "-" . $currentMonth . "-01") : $k;
        $endDate = empty($k1) ? date("Y-m-t", strtotime($startDate)) : $k1;
        $filterModel = new Filter();
        $filterModel->startDate = $startDate;
        $filterModel->endDate = $endDate;
        $service = new Service();
        $students = $service->getRegisteredStudents($startDate, $endDate);
        $datas = [];
        foreach ($students as $data) {
            $studentModel = new Student();
            $studentModel->setAttributes($data);
            $datas[] = $studentModel;
        }
        return $this->render('student-registration', ['datas' => $datas, 'filterModel' => $filterModel]);
    }

    public function actionPayments($k = "", $k1 = "", $k2 = "", $k3 = "") {
        $currentMonth = date("m");
        $currentYear = date("Y");
        $startDate = empty($k) ? ($currentYear . "-" . $currentMonth . "-01") : $k;
        $endDate = empty($k1) ? date("Y-m-t", strtotime($startDate)) : $k1;
        $filterModel = new Filter();
        $filterModel->startDate = $startDate;
        $filterModel->endDate = $endDate;

        $service = new Service();
        $revenueStreams = $service->revenueStream();
        $modes = $service->paymentMode();
        $dashboardData = $service->getDashboardTransactions($startDate, $endDate, $k2);
        $paymentData = [];
        foreach ($dashboardData as $payment) {
            if ($payment['feeCode'] != $k2 && !empty($k2)) {
                continue;
            }
            if ($k3 != $payment['channel'] && !empty($k3)) {
                continue;
            }
            $paymentModel = new Payments();
            $paymentModel->setAttributes($payment);
            $paymentModel->student = $payment['student'];
            $paymentData[] = $paymentModel;
        }
        return $this->render('payments', ['filterModel' => $filterModel, 'paymentData' => $paymentData, 'modes' => $modes, 'revenueStreams' => $revenueStreams]);
    }

    public function actionCourseApplications($k = "", $k1 = "", $k2 = "", $k3 = "") {
        $identity = Yii::$app->user->getIdentity();
        $currentMonth = date("m");
        $currentYear = date("Y");
        $filterModel = new Filter();
        $filterModel->startDate = empty($k) ? $currentYear . "-" . $currentMonth . "-01" : $k;
        $filterModel->endDate = empty($k1) ? date("Y-m-t", strtotime($filterModel->startDate)) : $k1;
        $filterModel->courseStatus = empty($k2) ? 2 : $k2;
        $filterModel->user = empty($k3) ? $identity->user['role']['description'] == 'superadmin' ? "" : $identity->id : $k3;

        $service = new Service();
        $applicationStatus = $service->courseApplicationStatus();
        $users = $service->getVerificationUsers();
        $studentsCourse = $service->getStudentsCourseApplication($filterModel->startDate, $filterModel->endDate, $filterModel->user);
        $registrations = [];
        $userData[] = 'All';
        foreach ($users as $user) {
            $userData[$user['id']] = $user['firstName'] . " " . $user['otherNames'];
        }

        foreach ($studentsCourse as $courses) {
            //print_r($courses); exit;
            if ($filterModel->courseStatus <= 1 && $filterModel->courseStatus != $courses['verified']) {
                continue;
            }
            $courseModel = new CourseDisplay();
            $courseModel->id = $courses['id'];
            $courseModel->verifiedBy = $courses['verifiedBy'];
            $courseModel->created = $courses['created'];
            $courseModel->dateVerified = $courses['dateVerified'];
            $courseModel->studentId = $courses['studentObj'];
            $courseModel->courseId = $courses['course'];
            $courseModel->verificationStatus = $courses['verificationStatus'];
            $registrations[] = $courseModel;
        }
        return $this->render('course-applications', ['userData' => $userData, 'filterModel' => $filterModel, 'registrations' => $registrations, 'applicationStatus' => $applicationStatus]);
    }

    public function actionDeclarations($k = "", $k1 = "") {
        $filterModel = new Filter();
        $filterModel->declrations = empty($k) ? "" : $k;
        $filterModel->response = empty($k1) ? "" : $k1;
        $service = new Service();
        $declarations = $service->getDeclarations();
        $datas = $service->getDeclarationReport($filterModel->declrations, $filterModel->response);
        $dataArray = [];
        $declarationsData[] = 'All';
        foreach ($declarations as $declaration) {
            $declarationsData[$declaration['id']] = $declaration['description'];
        }
        foreach ($datas as $data) {
            $modelData = new DeclarationReport();
            $modelData->setAttributes($data);
            $dataArray[] = $modelData;
        }
        return $this->render('declarations', ['filterModel' => $filterModel, 'dataArray' => $dataArray, 'declarationsData' => $declarationsData]);
    }

    public function actionExemptionApplications($k = "", $k1 = "", $k2 = 2, $k3 = "") {
        $identity = Yii::$app->user->getIdentity();
        $currentMonth = date("m");
        $currentYear = date("Y");
        $filterModel = new Filter();
        $filterModel->startDate = empty($k) ? $currentYear . "-" . $currentMonth . "-01" : $k;
        $filterModel->endDate = empty($k1) ? date("Y-m-t", strtotime($filterModel->startDate)) : $k1;
        $filterModel->courseStatus = $k2;
        $filterModel->user = empty($k3) ? $identity->user['role']['description'] == 'superadmin' ? "" : $identity->id : $k3;
        $service = new Service();
        $applicationStatus = $service->courseApplicationStatus();
        $users = $service->getVerificationUsers();
        $datas = $service->getExemptionsBookings($filterModel->startDate, $filterModel->endDate, $filterModel->user);
        //print_r($datas); exit;

administrator/views/reports/_courseApplication.php
<?php

use yii\data\ArrayDataProvider;
use yii\grid\GridView;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([
        'allModels' => $students,
            ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Name',
            'value' => function($data) {
                return $data->studentId['firstName']." ".$data->studentId['middleName']." ".$data->studentId['lastName'];
            }
        ],
        [
            'label' => 'Reg. Date',
            'value' => function($data) {
                return $data->created;
            }
        ],
        [
            'label' => 'Course',
            'value' => function($data) {
                return $data->courseId['name'];
            }
        ],
        [
            'label' => 'Verified By',
            'value' => function($data) {
                return !empty($data->verifiedBy) ? $data->verifiedBy['firstName']." ".$data->verifiedBy['otherNames'] : "-";
            }
        ],
        [
            'label' => 'Verified At',
            'value' => function($data) {
                return $data->dateVerified;
            }
        ],
        [
            'label' => 'Status',
            'value' => function($data) {
                return $data->verificationStatus;
            }
        ],
        ],
    ]);
?>

administrator/views/reports/_exam-booking.php
<?php

use yii\data\ArrayDataProvider;
use yii\grid\GridView;

?>
<?=

GridView::widget([
    'dataProvider' => new ArrayDataProvider(['allModels' => $datas]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],     
        [
            'label' => 'Name',
            'value' => function($data) {
                return $data->student['firstName']." ".$data->student['middleName']." ".$data->student['lastName'];
            }
        ],   
        [
            'label' => 'Phone No.',
            'value' => function($data) {
                return $data->student['phoneNumber'];
            }
        ], 
        [
            'label' => 'Reg. No.',
            'value' => function($data) {
                return $data->fullRegNo;
            }
        ],
        [
            'label' => 'Sitting',
            'value' => function($data) {
                return $data->sitting['sittingPeriod']." - ".$data->sitting['sittingYear'];
            }
        ],
        [
            'label' => 'Center',
            'value' => function($data) {
                return $data->sittingCentre['name'];
            },
            'headerOptions' => ['style' => 'max-width: 250px'],
            'contentOptions' => ['style' => 'max-width: 250px; word-wrap: break-word; overflow: auto;'],
        ],
        'status',
        [
            'label' => 'Timestamp',
            'value' => function($data) {
                return $data->created;
            }
        ],                
    ],
]);
?>

administrator/views/reports/_filterApplication.php
<?php
use kartik\date\DatePicker;
use kartik\form\ActiveForm;

$form = ActiveForm::begin([
            'id' => 'filter-details-form',
            'action' => Yii::$app->urlManager->createUrl(['reports/course-applications']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">   
            <div class="col-md-3">                            
                            <?= $form->field($model, 'user', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-user"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($userData) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'courseStatus', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-exchange"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($applicationStatus) ?>
                        </div>
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'startDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'endDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

administrator/views/reports/_filterDeclarations.php
<?php
use kartik\form\ActiveForm;

$form = ActiveForm::begin([
            'id' => 'filter-details-form',
            'action' => Yii::$app->urlManager->createUrl(['reports/declarations']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">   
            <div class="col-md-6"></div>             
            <div class="col-md-3">                            
                            <?= $form->field($model, 'declrations', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-user"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($declarationsData) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'response', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-exchange"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList([''=>'All','true'=>'Yes','false'=>'No']) ?>
                        </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

administrator/views/reports/_filterExamination.php
<?php

use kartik\form\ActiveForm;

$form = ActiveForm::begin([
            'id' => 'filter-details-form',
            'action' => Yii::$app->urlManager->createUrl(['reports/examination-booking']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">    
            <div class="col-md-3">                            
                            <?= $form->field($model, 'courseType', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-exchange"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($courseTypes) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'course', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-exchange"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($courses) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'year', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-calendar-o"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($sittingYears) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'month', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-calendar"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($sittingMonths) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'zone', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-building"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($zones) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'center', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-building"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($centers) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'status', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-building"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($status) ?>
                        </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

administrator/views/reports/_filterExemptionApplication.php
<?php
use kartik\date\DatePicker;
use kartik\form\ActiveForm;

$form = ActiveForm::begin([
            'id' => 'filter-details-form',
            'action' => Yii::$app->urlManager->createUrl(['reports/exemption-applications']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">   
            <div class="col-md-3">                            
                            <?= $form->field($model, 'user', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-user"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($userData) ?>
                        </div>
            <div class="col-md-3">                            
                            <?= $form->field($model, 'courseStatus', [
                                    'addon' => ['prepend' => ['content' => '<i class="fa fa-exchange"></i>']],
                                'inputOptions' => ['class' => 'form-control  form-control-custom'],
                            ])->dropDownList($applicationStatus) ?>
                        </div>
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'startDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'endDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

administrator/views/reports/_filterStudents.php
<?php
use kartik\date\DatePicker;
use kartik\form\ActiveForm;

$form = ActiveForm::begin([
            'id' => 'filter-details-form',
            'action' => Yii::$app->urlManager->createUrl(['reports/student-registration']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">      
            <div class="col-md-6"> </div> 
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'startDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
            <div class="col-md-3"> 

                <?=
                $form->field($model, 'endDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
                ?>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

administrator/views/reports/_payments.php
<?php

use yii\data\ArrayDataProvider;
use yii\grid\GridView;

?>
<?=

GridView::widget([
    'dataProvider' => new ArrayDataProvider(['allModels' => $payments]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Student',
            'value' => function($data) {
                return $data->student['firstName']." ".$data->student['middleName']." ".$data->student['lastName'];
            }
        ],
        [
            'label' => 'Registration Number',
            'value' => function($data) {
                return $data->fullRegNo;
            }
        ],
        [
            'label' => 'Channel',
            'value' => function($data) {
                return $data->channel;
            }
        ],
        'phoneNumber',
        [
            'label' => 'Revenue Stream',
            'value' => function($data) {
                return str_replace("_", " ", $data->feeCode) ;
            }
        ],
        [
            'label' => 'Timestamp',
            'value' => function($data) {
                return $data->paymentTimestamp;
            }
        ],
        [
            'attribute' => 'amount',
            'value' => function($data) {
                return $data->currency . " " . number_format($data->amount, 2);
            },
            'contentOptions' => ['style' => 'text-align:right;'],
            'headerOptions' => ['style' => 'text-align:right;'],
        ],
                
    ],
]);
?>

administrator/views/reports/course-applications.php
<?php
$this->title = Yii::t('app', 'Course Applications');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <div class="alert alert-danger" style="display: none;" id="dashboard-filter-error"></div>

                <div class="row" style="background-color: #f5f5f0; margin-right: 0px; margin-left: 0px; margin-bottom:30px;">
                    <div class="col-md-11">
                        <?= $this->render('_filterApplication', ['userData'=>$userData,'model' => $filterModel, 'applicationStatus' => $applicationStatus]) ?>
                    </div>
                    <div class="col-md-1" style="padding-top: 25px; padding-left: 0px;">
                        <button class = "btn btn-sm btn-primary" id= "filter-course-application" ><span clasfilter-course-applications="fa fa-search"></span>Search</button>
                    </div>
                </div>
                <div class="row text-right" style="margin-right: 0px; margin-left: 0px; margin-bottom: 20px;" >
                    <!--<button class = "btn btn-sm btn-success"  id= "pdf-students" ><span class="fa fa-file"></span> Export PDF</button>-->
                    <button class = "btn btn-sm btn-primary"  id= "excel-course-application" ><span class="fa fa-download"></span> Export Excel</button>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->render('_courseApplication', ['students' => $registrations]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/reports/declarations.php
<?php
$this->title = Yii::t('app', 'Declarations');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <div class="alert alert-danger" style="display: none;" id="dashboard-filter-error"></div>

                <div class="row" style="background-color: #f5f5f0; margin-right: 0px; margin-left: 0px; margin-bottom:30px;">
                    <div class="col-md-11">
                        <?= $this->render('_filterDeclarations', ['model' => $filterModel, 'declarationsData' => $declarationsData]) ?>
                    </div>
                    <div class="col-md-1" style="padding-top: 25px; padding-left: 0px;">
                        <button class = "btn btn-sm btn-primary" id= "filter-declarations" ><span class="fa fa-search"></span>Search</button>
                    </div>
                </div> 
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->render('_declarations', ['datas' => $dataArray]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/reports/miscellaneous.php
<?php
$this->title = Yii::t('app', 'Miscellaneous');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>