administrator/controllers/ExemptionController.php
<?php

namespace administrator\controllers;

use common\models\ExemptionVerification;
use common\models\Service;
use common\models\Student;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use common\models\Institutions;
use common\models\ExemptionCourse;
use common\models\ExemptionCoursePapers;
use common\models\InstitutionCourses;

/**
 * Site controller
 */
class ExemptionController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionView($id) {
        $service = new Service();
        $studentModel = new Student();
        $exemptions = $service->getExemption($id);
        $studentModel->setAttributes($exemptions['student']);
        $remarks = $service->rejectionReasonsExemption();
        return $this->render('view', ['model' => $studentModel, 'exemptions' => $exemptions, 'remarks' => $remarks]);
    }

    public function actionIndex() {
        $service = new Service();
        $model = new ExemptionVerification();
        $datas = $service->getPendingExemptions();
        $remarks = $service->rejectionReasonsExemption();
        $dataArray = [];
        foreach ($datas as $data) {
            $modelData = new ExemptionVerification();
            $modelData->setAttributes($data);
            $modelData->studentId = $data['student'];
            //print_r($modelData->studentId); exit;
            $dataArray[] = $modelData;
        }
        return $this->render('pending', ['model' => $model, 'datas' => $dataArray, 'remarks' => $remarks]);
    }

    public function preparePapersData($data) {
        $datas = explode(',', $data);
        $papers = [];
        for ($i = 0; $i < count($datas) - 1; $i++) {
            $papers[] = ['code' => $datas[$i]];
        }
        return $papers;
    }

    public function actionVerify($id, $courseId, $studentId, $type) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new ExemptionVerification();
        $checked = isset($_POST['checked']) ? $_POST['checked'] : "";
        $remarks = isset($_POST['remarks']) ? $_POST['remarks'] : "";
        $password = isset($_POST['password']) ? $_POST['password'] : "";
        $datatosend = isset($_POST['datatosend']) ? $_POST['datatosend'] : "";
        if (!empty($checked) && !empty($password)) {
            $remarks = $checked == "APPROVED" ? "" : $remarks;
            if ($type != "all-summary" && ($type == "all-partial" || $type = "all-single") && empty($datatosend)) {
                $model->addError("", "You must select atleast one paper");
            } else {
                $service = new Service();
                $identity = Yii::$app->user->getIdentity();
                $studentModel = new Student();
                $exemptions = $service->getExemption($id);
                $papers = [];
                if ($type == "all-partial") {
                    $papers = $this->preparePapersData($datatosend);
                }
                if ($type == "all-single") {
                    $papers[] = ['code' => $datatosend];
                }
                if ($type == "all-summary") {
                    $courseId = $studentModel->currentCourse['id'];
                    foreach ($exemptions['papers'] as $paper) {
                        $papers[] = ['code' => $paper['paper']['code']];
                    }
                }
                $papersData = [];
                foreach ($papers as $pp) {
                    $papersData[] = [
                        'paper' => $pp,
                        'verificationStatus' => $checked,
                        'remarks' => $remarks,
                    ];
                }

                $data = [
                    'id' => $id,
                    'papers' => $papersData,
                    'verifiedBy' => ['id' => $identity->user['id']],
                ];
                $response = (object) $service->verifyExemption($data);
                if ($response->status['code'] == 1) {
                    Yii::$app->session->setFlash('success-message', 'Verification process was successful...');
                    $url = Url::toRoute(['exemption/index']);
                    return ['success' => ['url' => $url]];
                } else {
                    $model->addError("", "ERROR CODE " . $response->status['code'] . " :: " . $response->status['message']);
                }
            }
        } else {
            $model->addError("", "All fields are mandatory");
        }
        $errorsArry = '';
        foreach ($model->getErrors() as $error) {
            $errorsArry .= $error[0] . "<br/>";
        }
        return ['error' => $errorsArry];
    }

    public function actionInstitution() {
        $service = new Service();
        $model = new Institutions();
        $institutionData = $service->getInstitutions();
        $institutions = $qualificationTypes = [];
        foreach ($institutionData as $data) {
            $institutionModel = new Institutions();
            $institutionModel->setAttributes($data);
            $institutionModel->courseCount = count($institutionModel->courses);
            $institutions[] = $institutionModel;
        }
        $qualificationType = $service->getCourseTypeOthers();
        foreach ($qualificationType as $data) {
            $qualificationTypes[$data['code']] = $data['name'];
        }
        return $this->render('institutions', ['model' => $model, 'datas' => $institutions, 'qualificationTypes' => $qualificationTypes]);
    }

    public function actionViewInstitution($id) {
        $service = new Service();
        $model = new Institutions();
        $exemptionCourseModel = new ExemptionCourse();
        //$model->setAttributes($service->getInstitution($id));
        $institutionData = $service->getInstitutions();
        $courses = $coursesArray = $coursePapers = [];
        foreach ($institutionData as $data) {
            if ($id == $data['id']) {
                $model->setAttributes($data);
                foreach ($data['courses'] as $course) {
                    $institutionCourseModel = new InstitutionCourses();
                    $institutionCourseModel->setAttributes($course);
                    $institutionCourseModel->institutionId = $id;
                    $courses[] = $institutionCourseModel;
                }
                $model->courseCount = count($courses);
            }
        }
        $exemptionCourseModel->institutionId = $id;
        $exemptionCourseModel->courseType = $model->courseType['code'];
        return $this->render('view-exemption', ['exemptionCourseModel' => $exemptionCourseModel, 'model' => $model, 'courses' => $courses, 'coursesArray' => $coursesArray, 'coursePapers' => $coursePapers]);
    }

    public function actionViewInstitutionCourse($institutionId, $id) {
        $service = new Service();
        $exemptionCourseModel = new ExemptionCourse();
        $model = new ExemptionCoursePapers();
        $model->courseId = $id;
        $model->institutionId = $institutionId;
        $exemptionCourse = $service->getInstitutionCourse($id);
        $exemptionCourseModel->id = $exemptionCourse['id'];
        $exemptionCourseModel->courseName = $exemptionCourse['name'];
        $exemptionCourseModel->institutionId = $exemptionCourse['institutionName'];
        $exemptionCourseModel->institution = $exemptionCourse['institutionId'];
        $coursesArray = $coursePapers = $papers = [];
        $coursesData = $service->getAllCourses();
        $i = 0;
        foreach ($coursesData as $course) {
            $coursesArray[$course['id']] = $course['name'];
            if ($i == 0) {
                foreach ($course['papers'] as $paper) {
                    $coursePapers[$paper['code']] = $paper['name'];
                }
            }
            $i++;
        }

        foreach ($exemptionCourse['exemptionCourses'] as $courses) {
            foreach ($courses['papers'] as $course) {
                $exemptionCoursePapers = new ExemptionCoursePapers();
                $exemptionCoursePapers->setAttributes($course);
                $exemptionCoursePapers->courseId = ['id' => $courses['id'], 'name' => $courses['name']];
                $papers[] = $exemptionCoursePapers;
                //print_r($exemptionCoursePapers); exit;
            }
        }
        $exemptionCourseModel->papers = count($papers);
        return $this->render('view-institution-course', ['model' => $model, 'exemptionCourseModel' => $exemptionCourseModel, 'coursesArray' => $coursesArray, 'coursePapers' => $coursePapers, 'papers' => $papers]);
    }

    public function actionCreateInstitutionCoursePaperFilter($courseId) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $coursePapers = [];
        $service = new Service();
        $coursesData = $service->getAllCourses();
        foreach ($coursesData as $course) {
            if ($course['id'] == $courseId) {
                foreach ($course['papers'] as $paper) {
                    $coursePapers[$paper['code']] = $paper['name'];
                }
            }
        }
        return ['success' => $coursePapers];
    }

    public function actionCreateInstitutionCoursePaper() {
        Yii::$app->response->format = Response::FORMAT_JSON;

administrator/views/exemption/_courseform.php
<?php
use kartik\form\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin([
            'id' => 'exemption-course-papers-form',
            'action' => Yii::$app->urlManager->createUrl(['exemption/create-institution-course']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<?= Html::activeHiddenInput($model, 'institutionId') ?>
<?= Html::activeHiddenInput($model, 'courseType') ?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">    
            <div class="col-md-12">                      
                <?=
                $form->field($model, 'courseName', [
                    'addon' => ['prepend' => ['content' => '<i class="fa fa-tasks"></i>']],
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>
<h2></h2>
<div class="alert alert-danger"  id="error-summary" style="display: none;"></div>
<h2></h2>
<div id="progress-spinner" class="text-center" style="display: none;">
    <?= Html::img('@web/images/ajax-loader.gif', ['alt' => 'progress spinner']) ?>
</div>
<h2></h2>

administrator/views/exemption/_courses.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
$url = Url::toRoute(['exemption/verify', 'id' => $courses['id'], 'courseId' => $courses['studentCourseId'], 'studentId' => $model->id, 'type' => 'all-single']);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Current Course Details</strong>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered">
            <tr><th>Reg. No.</th><td><?= $courses['fullRegNo'] ?></td></tr>
        </table>
    </div>
    <div class="panel-heading">
        <strong>Application Grounds</strong>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered">
            <?php foreach ($courses['documents'] as $doc) : ?>
                <tr>
                    <th>Transcript</th>
                    <td><a href="<?=Yii::$app->params['studentPortalUrl']?>/students/exemptions/<?=$doc['name']?>" target="_blank">click to preview</a> &nbsp;  &nbsp;  &nbsp; <a href="<?=Yii::$app->params['studentPortalUrl']?>/students/exemptions/<?=$doc['name']?>" download>Download</a></td>
                </tr>
            <?php endforeach; ?>
        </table>
          
    </div>
    <div class="panel-heading">
        <strong>Exemption Details</strong>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Paper Code</th>
                <th>Paper Name</th>
                <th><input type="checkbox" id="exemptionpapersall"></th>
                <th></th>
            </tr>
            <?php foreach ($courses['papers'] as $paper) : ?>
                <tr>
                    <td><?= $paper['paper']['code'] ?></td>
                    <td><?= $paper['paper']['name'] ?></td>
                    <td><input type="checkbox" class="exemptionpapers" name="exemptionpapers" value="<?= $paper['paper']['code'] ?>"></td>
                    <td><?= Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, ['data-whatever' => $url, 'data-toggle' => "modal", 'data-target' => "#VerifyExemptionRedirectModal", 'data-type' => $paper['paper']['code'], 'title' => Yii::t('yii', 'Verify'),]) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

administrator/views/exemption/_data.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
use yii\bootstrap\Modal;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([ 'allModels' => $students, ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Student',
            'value' => function($data) {
                return $data->studentId['firstName']." ".$data->studentId['middleName']." ".$data->studentId['lastName'];
            }
        ],
        [
            'label' => 'Registration Number',
            'value' => function($data) {
                return $data->fullRegNo;
            }
        ],
        [
            'attribute' => 'qualification',
            'value' => function($data) {
                return $data->type;
            }
        ],
        
        [
            'class' => 'yii\grid\CheckboxColumn',
            'checkboxOptions' => function ($model, $key, $index, $column) {
                return ['value' => $model->id];
            },
            'name' => 'id',
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{verify}&nbsp;&nbsp;',
            'buttons' => [
                    'view' => function($url, $model) {
                        $url = Url::toRoute(['exemption/view', 'id' => $model->id]);
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => 'View']);
                    },
                    'verify' => function($url,$model){
                        $url = Url::toRoute(['exemption/verify','id'=>$model->id,'courseId'=>$model->studentCourseId,'studentId'=>$model->studentId['id'],'type'=>'all-summary']);
                        return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, ['data-whatever'=>$url, 'data-toggle'=>"modal", 'data-type'=>'all-summary', 'data-target'=>"#VerifyExemptionRedirectModal",'title' => Yii::t('yii', 'Verify'),]);
                    },
                ],
            ],
        ],
    ]);
?>

<!-- Verification Modal -->
<?php
    Modal::begin([
        'id' => 'VerifyExemptionRedirectModal',
        'header' => '<h4 class="modal-title" >Record Verification</h4>',
        'footer' =>
            Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
            . PHP_EOL .
            Html::button('Verify', ['id' => 'verify-redirect-btn', 'class' => 'btn btn-primary btn-modal-save']),
    ]);
?>
<?= $this->render('@common/views/_verify',['remarks'=>$remarks]) ?>
<?php Modal::end() ?>

administrator/views/exemption/_form.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

administrator/views/exemption/_institution.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([ 'allModels' => $institutions, ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'name',
            'value' => function($data) {
                return $data->name;
            }
        ],
        [
            'label' => 'Course Type',
            'value' => function($data) {
                return $data->courseType['name'];
            }
        ],
        [
            'label' => 'Number of Course',
            'value' => function($data) {
                return $data->courseCount;
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{delete}&nbsp;&nbsp;',
            'buttons' => [
                    'view' => function($url, $model) {
                        $url = Url::toRoute(['exemption/view-institution', 'id' => $model->id]);
                        return Html::a('view', $url, ['title' => 'View']);
                    },
                    'delete' => function($url,$model){
                        $url = Url::toRoute(['exemption/delete-institution', 'id' => $model->id]);
                        return Html::a('delete', $url, ['title' => 'Delete']);
                    },
                ],
            ],
        ],
    ]);
?>

administrator/views/exemption/_institutioncourses.php
<?php

use yii\data\ArrayDataProvider;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([ 'allModels' => $courses, ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Name',
            'value' => function($data) {
                return $data->name;
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{delete}&nbsp;&nbsp;',
            'buttons' => [
                    'view' => function($url, $model) {
                        $url = Url::toRoute(['exemption/view-institution-course', 'institutionId' => $model->institutionId, 'id' => $model->id]);
                        return Html::a('view', $url, ['title' => 'View']);
                    },
                    'delete' => function($url,$model){
                        $url = Url::toRoute(['exemption/delete-institution-course', 'institutionId' => $model->institutionId, 'id' => $model->id]);
                        return Html::a('delete', $url, ['title' => 'Delete']);
                    },
                ],
            ],
        ],
    ]);
?>

administrator/views/exemption/_institutioncoursesummary.php
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8 personal-details-div">Details</div>
         </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Course Name") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->courseName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Institution") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->institutionId ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Papers Count") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->papers ?></div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/exemption/_institutionform.php
<?php
use kartik\form\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin([
            'id' => 'exemption-institution-form',
            'action' => Yii::$app->urlManager->createUrl(['exemption/create-institution']),
            'options' => ['enctype' => 'multipart/form-data',],
            'fieldConfig' => [
                'template' => "{label}{input}\n{hint}\n{error}",
            ],
        ]);
?>
<div class="row">
    <div class="col-md-12">
        <div class="row form-row-below">    
            <div class="col-md-6">                            
                <?=
                $form->field($model, 'courseType', [
                    'addon' => ['prepend' => ['content' => '<i class="fa fa-tasks"></i>']],
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->dropDownList($qualifications)
                ?>
            </div>
            <div class="col-md-6">                            
                <?=
                $form->field($model, 'name', [
                    'addon' => ['prepend' => ['content' => '<i class="fa fa-tasks"></i>']],
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>
<h2></h2>
<div class="alert alert-danger"  id="error-summary" style="display: none;"></div>
<h2></h2>
<div id="progress-spinner" class="text-center" style="display: none;">
    <?= Html::img('@web/images/ajax-loader.gif', ['alt' => 'progress spinner']) ?>
</div>
<h2></h2>

administrator/views/exemption/_institutionsummary.php
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8 personal-details-div">Details</div>
         </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Institution Name") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->name ?></div>
                </div>
                <div class="row profile-info-row" style="margin-bottom: 10px; margin-top: 10px;">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Course Type") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->courseType['name'] ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("Course Count") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->courseCount ?></div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/exemption/_profile.php
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8 personal-details-div">Personal Details</div>
         </div>
    </div>
    <div class="panel-body">
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-md-5">
                <img src="<?=Yii::$app->params['studentPortalUrl']?>/students/documents/<?= $passport ?>" class=" img-responsive" > 
             </div>
            <div class="col-md-4"></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("firstName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->firstName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("middleName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->middleName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("lastName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->lastName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("nationality") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->nationality['nationality'] ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("documentNo") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->documentNo ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("dob") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->dob ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("gender") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $gender ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("email") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->email ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("phoneNumber") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->phoneNumber ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("contact") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->contact['postalAddress'] . " - " . $model->contact['postalCode'] . " " . $model->contact['town'] ?></div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/exemption/institutions.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;

$this->title = Yii::t('app', 'Exemption Institutions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
                <?php endif; ?>
                <?php if (Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
                <?php endif; ?>
                <p class="text-right"><button class="btn btn-sm btn-primary" data-whatever="" data-toggle="modal" data-target="#NewInstitutionModal"><span class="glyphicon glyphicon-plus"></span> New Institution</button></p>
                <?= $this->render('_institution', ['model' => $model, 'institutions' => $datas]) ?>
            </div>
        </div>
    </div>
</div>


<!-- Institution Modal -->
<?php
Modal::begin([
    'id' => 'NewInstitutionModal',
    'header' => '<h4 class="modal-title" >New Institution</h4>',
    'footer' =>
    Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
    . PHP_EOL .
    Html::button('Add Institution', ['id' => 'new-institution-btn', 'class' => 'btn btn-primary btn-modal-save']),
]);
?>
<?= $this->render('_institutionform', ['qualifications' => $qualificationTypes, 'model' => $model]) ?>
<?php Modal::end() ?>

administrator/views/exemption/pending.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Modal;
$this->title = Yii::t('app', 'Students\' Exemption Verification');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <!--<p class="text-right"><button class="btn btn-sm btn-primary" data-whatever="" data-toggle="modal" data-target="#BatchVerificationModal">Batch Verification</button></p>-->
                <?= $this->render('_data', [ 'model' => $model,'students'=>$datas,'remarks'=>$remarks]) ?>
            </div>
        </div>
    </div>
</div>


<!-- Verification Modal -->
<?php
    Modal::begin([
        'id' => 'VerifyRedirectModal',
        'header' => '<h4 class="modal-title" >Record Verification</h4>',
        'footer' =>
            Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
            . PHP_EOL .
            Html::button('Verify', ['id' => 'verify-redirect-btn', 'class' => 'btn btn-primary btn-modal-save']),
    ]);
?>
<?= $this->render('@common/views/_verify',['remarks'=>$remarks]) ?>
<?php Modal::end() ?>