administrator/controllers/IdentificationController.php
<?php

namespace administrator\controllers;

use common\models\CourseDisplay;
use common\models\Service;
use common\models\Student;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class IdentificationController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionView($id) {
        $service = new Service();
        $studentModel = new Student();
        $studentModel->setAttributes($service->getStudentData($id));
        $courses = null;
        foreach ($studentModel->studentCourses as $course) {
            if (!$course['verified']) {
                $courses = $course;
            }
        }
        $remarks = $service->rejectionReasonsRegistration();
        return $this->render('view', ['model' => $studentModel, 'courses' => $courses, 'remarks' => $remarks]);
    }

    public function actionIndex() {
        $service = new Service();
        $studentModel = new Student();
        $studentsIdentifications = $service->getStudentsPendingIdentifications();

        $registrations = [];
        foreach ($studentsIdentifications as $courses) {
            $courseModel = new CourseDisplay();
            $courseModel->registrationNumber = $courses['fullRegistrationNumber'];
            $courseModel->id = $courses['id'];
            $courseModel->created = $courses['created'];
            $courseModel->studentId = $courses['studentObj'];
            $courseModel->courseId = $courses['course'];
            $registrations[] = $courseModel;
        }
        return $this->render('pending', ['model' => $studentModel, 'datas' => $registrations]);
    }

    public function actionVerify($courseId, $courseStatus) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $service = new Service();
        $model = new CourseDisplay();
        $identity = Yii::$app->user->getIdentity();
        $data = ['id' => $courseId, 'courseStatus' => $courseStatus,'verifiedBy'=>['id'=>$identity->user['id']]];
        $response = (object) $service->verifySignupIdentification($data);
        if ($response->status['code'] == 1) {
            Yii::$app->session->setFlash('success-message', 'Verification process was successful...');
            return $this->redirect(['identification/index']);
        } else {
            $model->addError("", "ERROR CODE " . $response->status['code'] . " :: " . $response->status['message']);
        }
        $errorsArry = '';
        foreach ($model->getErrors() as $error) {
            $errorsArry .= $error[0] . "<br/>";
        }
        return ['error' => $errorsArry];
    }

}

administrator/controllers/RegistrationController.php
<?php

namespace administrator\controllers;

use common\models\CourseDisplay;
use common\models\Service;
use common\models\Student;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class RegistrationController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionView($id) {
        $service = new Service();
        $studentModel = new Student();
        $studentModel->setAttributes($service->getStudentData($id));
        $courses = null;
        foreach ($studentModel->studentCourses as $course) {
            if (!$course['verified']) {
                $courses = $course;
            }
        }
        $remarks = $service->rejectionReasonsRegistration();
        return $this->render('view', [ 'model' => $studentModel, 'courses' => $courses,'remarks'=>$remarks]);
    }

    public function actionIndex() {
        $service = new Service();
        $studentModel = new Student();
        $studentsCourse = $service->getStudentsPending();
        $remarks = $service->rejectionReasonsRegistration();
        
        $registrations = [];
        foreach ($studentsCourse as $courses) {
            $courseModel = new CourseDisplay();
            $courseModel->id = $courses['id'];
            $courseModel->created = $courses['created'];
            $courseModel->studentId = $courses['studentObj'];
            $courseModel->courseId = $courses['course'];
            $registrations[] = $courseModel;
        }
        return $this->render('pending', [ 'model' => $studentModel, 'datas' => $registrations,'remarks'=>$remarks]);
    }

    public function actionVerify($courseId, $type) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $service = new Service();
        $model = new CourseDisplay();
        $checked = isset($_POST['checked']) ? $_POST['checked'] : "";
        $remarks = isset($_POST['remarks']) ? $_POST['remarks'] : "";
        $password = isset($_POST['password']) ? $_POST['password'] : "";
        $dataToSend = isset($_POST['datatosend']) ? $_POST['datatosend'] : "";
        if (!empty($checked) && !empty($password)) {
            $remarks = $checked == "APPROVED" ? "" : $remarks;
            $courseData = [];
            if ($type == "partial") {
                //prepare partial batch verification data
                $partial = explode(',', $dataToSend);
                for ($i = 0; $i < count($partial) - 1; $i++) {
                    $courseData[] = [
                        'id' => $partial[$i]
                    ];
                }
            }
            if ($type == "all") {
                //prepare all batch verification data
                $studentsCourse = $service->getStudentsPending();
                foreach ($studentsCourse as $courses) {
                    $courseData[] = [
                        'id' => $courses['id']
                    ];
                }
            }

            if ($type == "single") {
                //prepare single verification
                $courseData = [
                    'id' => $courseId,
                ];
            }
            if (!empty($courseData)) {
                $identity = Yii::$app->user->getIdentity();
                if ($type === "single") {
                    $data = [
                        'id' => $courseData['id'],
                        'verifiedBy' => ['id'=>$identity->user['id']],
                        'remarks' => $remarks,
                        'rejectCode' => $remarks,
                        'verificationStatus' => $checked
                    ];
                } else {
                    $data = [
                        'studentCourses' => $courseData,
                        'verifiedBy' => $identity->user['id'],
                        'remarks' => $remarks,
                        'rejectCode' => $remarks,
                        'verificationStatus' => $checked
                    ];
                }
                $response = (object) $service->verifyRegistration($data,$type);
                if ($response->status['code'] == 1) {
                    Yii::$app->session->setFlash('success-message', 'Verification process was successful...');
                    $url = Url::toRoute(['registration/index']);
                    return ['success' => ['url' => $url]];
                } else {
                    $model->addError("", "ERROR CODE " . $response->status['code'] . " :: " . $response->status['message']);
                }
            }
        } else {
            $model->addError("", "All fields are mandatory");
        }
        $errorsArry = '';
        foreach ($model->getErrors() as $error) {
            $errorsArry.=$error[0] . "<br/>";
        }
        return ['error' => $errorsArry];
    }

}

administrator/views/identification/_courses.php
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Course Details</strong>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered">
            <tr><th>Course Name</th><td><?= $courses['course']['name'] ?></td></tr>
            <tr><th>Date</th><td><?= $courses['created'] ?></td></tr>
            <?php if (!empty($courses['documents'])) { ?> 
                <tr>
                    <th>Documents</th>
                    <td>
                        <?php
                        foreach ($courses['documents'] as $document) {
                            ?>
                            <a href="<?= Yii::$app->params['studentPortalUrl'] ?>/students/qualifications/<?= $document['name'] ?>" target="_blank">preview</a>/<a href="<?= Yii::$app->params['studentPortalUrl'] ?>/students/qualifications/<?= $document['name'] ?>" download>Download</a> , &nbsp;  &nbsp; 
                            <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>

administrator/views/identification/_form.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

administrator/views/identification/_profile.php
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8 personal-details-div">Personal Details</div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-md-5">
                <img src="<?=Yii::$app->params['studentPortalUrl']?>/students/documents/<?= $passport ?>" style="height:120px;width:120px;" > 
             </div>
            <div class="col-md-4"></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("firstName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->firstName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("middleName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->middleName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("lastName") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->lastName ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("nationality") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->nationality['nationality'] ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("dob") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->dob ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("gender") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $gender ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("email") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->email ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("phoneNumber") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->phoneNumber ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("contact") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->contact['postalAddress'] . " - " . $model->contact['postalCode'] . " " . $model->contact['town'] ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("documentNo") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->documentNo ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong><?= $model->getAttributeLabel("documentType") ?></strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><?= $model->documentType['name'] ?></div>
                </div>
                <div class="row profile-info-row">  
                    <div class="col-md-4"><strong>Document</strong></div>
                    <div class="col-md-1"><strong>:</strong></div>
                    <div class="col-md-7"><a href="<?=Yii::$app->params['studentPortalUrl']?>/students/documents/<?=$model->documentScan?>" target="_blank">click to preview</a> &nbsp;  &nbsp;  &nbsp; <a href="<?=Yii::$app->params['studentPortalUrl']?>/students/documents/<?=$model->documentScan?>"  download > Download </a></div>
                </div>
            </div>
        </div>
    </div>
</div>

administrator/views/identification/_students.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=

GridView::widget([

    'dataProvider' => new ArrayDataProvider([
        'allModels' => $students,
            ]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Name',
            'value' => function($data) {
                return $data->studentId['firstName']." ".$data->studentId['middleName']." ".$data->studentId['lastName'];
            }
        ],
        [
            'label' => 'Reg. No',
            'value' => function($data) {
                return $data->registrationNumber;
            }
        ],
        [
            'label' => 'Phone Number',
            'value' => function($data) {
                return $data->studentId['phoneNumber'];
            }
        ],
        [
            'label' => 'Reg. Date',
            'value' => function($data) {
                return $data->created;
            }
        ],
        [
            'label' => 'Course',
            'value' => function($data) {
                return $data->courseId['name'];
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{approve}&nbsp;&nbsp;{reject}&nbsp;&nbsp;',
            'buttons' => [
                    'view' => function($url, $model) {
                        $url = Url::toRoute(['identification/view', 'id' => $model->studentId['id']]);
                        return Html::a('view', $url, ['title' => 'View']);
                    },
                    'approve' => function($url,$model){
                        $url = Url::toRoute(['identification/verify','courseId'=>$model->id, 'courseStatus'=>"ACTIVE"]);
                        return Html::a('approve', $url, ['style' => 'color:#00a65a;', 'title' => Yii::t('yii', 'Approve'),]);
                    },
                    'reject' => function($url,$model){
                        $url = Url::toRoute(['identification/verify','courseId'=>$model->id, 'courseStatus'=>"FAILED_IDENTIFICATION"]);
                        return Html::a('reject', $url, ['style' => 'color:#dd4b39;', 'title' => Yii::t('yii', 'Reject'),]);
                    },
                ],
            ],
        ],
    ]);
?>

administrator/views/identification/pending.php
<?php
use yii\helpers\Url;
$this->title = Yii::t('app', 'Students\' Signup Verification');
$this->params['breadcrumbs'][] = $this->title;
$url = Url::toRoute(['registration/verify','courseId'=>'']);
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <?= $this->render('_students', [ 'model' => $model,'students'=>$datas]) ?>
            </div>
        </div>
    </div>
</div>

administrator/views/identification/view.php
<?php
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
$url = Url::toRoute(['identification/verify','courseId'=>$courses['id'],"courseStatus"=>"ACTIVE"]);
$rejectUrl = Url::toRoute(['identification/verify','courseId'=>$courses['id'],"courseStatus"=>"FAILED_IDENTIFICATION"]);
$this->title = Yii::t('app', 'Student Profile');
$this->params['breadcrumbs'][] = $this->title;
$passport = empty($model->passportPhoto) ? "placeholder.jpg" : $model->passportPhoto;
$gender = empty($model->gender) ? "" : ($model->gender == 1 ? "Male" : "Female");
$documentType = empty($model->documentType) ? "ID No." : ($model->documentType == 1 ? "ID No." : ($model->documentType == 2 ? "Birth Cert. No." : "Passport No."));
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="fa fa-user"></span> <?=$this->title?></div>
            <div class="panel-body">
                <?php if(Yii::$app->session->hasFlash('fail-message')): ?>
                    <div class="alert alert-danger"><?=Yii::$app->session->getFlash('fail-message')?></div>
                <?php endif; ?>
                <?php if(Yii::$app->session->hasFlash('success-message')): ?>
                    <div class="alert alert-success"><?=Yii::$app->session->getFlash('success-message')?></div>
                <?php endif; ?>
                <p class="text-right">
                    <a class="btn btn-sm btn-success" href="<?=$url?>" >approve</a>
                    <a class="btn btn-sm btn-danger" href="<?=$rejectUrl?>" >reject</a>
                </p>
                 <div class="row">
                    <div class="col-md-5">
                        <?= $this->render('_profile', [ 'model' => $model,'passport'=>$passport,'gender'=>$gender,"documentType"=>$documentType]) ?>
                    </div>
                    <div class="col-md-7">
                        <?= $this->render('_courses', [ 'courses' => $courses]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Verification Modal -->
<?php
    Modal::begin([
        'id' => 'VerifyRedirectModal',
        'header' => '<h4 class="modal-title" >Record Verification</h4>',
        'footer' =>
            Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal'])
            . PHP_EOL .
            Html::button('Verify', ['id' => 'verify-redirect-btn', 'class' => 'btn btn-primary btn-modal-save']),
    ]);
?>
<?= $this->render('@common/views/_verify',['remarks'=>$remarks]) ?>
<?php Modal::end() ?>